### ISSUE TITLE
Module failing to load on Nuxt 3.0.0-rc.4 

### ISSUE THREAD

**Issue by gregmulvaney** [nuxt-community/supabase-module#54] opened 2022-06-27 14:33 UTC
### Version
@nuxtjs/supabase: 0.1.17
nuxt: 3.0.0-rc.4

### Reproduction Link
https://github.com/gregmulvaney/supabase_error

### Steps to reproduce
- Fresh Nuxt 3 app generated with Nuxi 
- Install @nuxtjs/supabase 
- Add entry to Nuxt build modules
- Run nuxt dev 

### What is Expected?
It works

### What is actually happening?
While Vite does start up, as soon as you attempt to load the site in a browser it hangs and then eventually returns a 503. Console outputs 
`Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use node --trace-warnings ...to show where the warning was created)
`

Removing @nuxtjs/supabase from the modules list fixes this error.

### Update
I am amble to use the module if I run `nuxt build` and `nuxt preview`. Still does not work with `nuxt dev`

**Comment by barthr** [comment] 2022-06-27 15:58
Same issue here

**Comment by gregmulvaney** [comment] 2022-06-27 18:34
I've found a temporary fix in disabling SSR in my Nuxt Config.

**Comment by oripka** [comment] 2022-06-27 18:35
Same here tried `"type": "module" in the package.json` but didn't help at all. As this was happening after not touching an existing project for a while it was a bit harder to track down. `--trace-warnings` didn't help either.

**Comment by oripka** [comment] 2022-06-27 18:42
> I've found a temporary fix in disabling SSR in my Nuxt Config.

Works for me

**Comment by gregmulvaney** [comment] 2022-06-28 03:55
The issue seems to be with `pathe@0.3.1` released earlier today. 

Downgraded to maximum `version 0.3.0` and everything is working now.

`
"resolutions": {
    "pathe": "<=0.3.0",
  }
`

**Comment by larbish** [comment] 2022-06-28 13:44
After digging a lot in sub dependencies, I finally found the guilty. I'll soon provide a release to fix it. To fix it temporary, can you try to add a `resolutions` field in your `package.json` with: 

```
"resolutions": {
    "@supabase/postgrest-js": "0.37.3"
}
```

**Comment by chris-visser** [comment] 2022-06-28 21:51
For me that solution didnt work since my supabase implementation was via @nuxtjs/supabase. What helped in this case was to add `**/` in front of the package name:

```
  "resolutions": {
    "**/@supabase/postgrest-js": "0.37.3"
  },
```

I'm curious as to why this could fail without version bump. Shouldnt minor changes of dependencies also be reflected into minor changes of the main package? This could theoretically break production builds or am I missing something?

With all due respect btw.. I really like Supabase!

**Comment by y-migita** [comment] 2022-06-29 04:39
same issue

**Comment by pi0** [comment] 2022-06-29 08:13
Thanks for making the issue and reproducing with the latest working version. I've managed to find the fix but worth sharing the story.

First thing first, in order to find more information about cause of error, as Node.js message tells, we can use `--trace-warnings`:

```sh
$ node --trace-warnings node_modules/.bin/nuxi dev

/home/pooya/tmp/supabase_error/node_modules/@supabase/postgrest-js/dist/module/lib/types.js:10
export class PostgrestBuilder {
^^^^^^

SyntaxError: Unexpected token 'export'
```

This means our dev bundle is importing an invalid ESM module. [Read More in v3 Docs about invalid ESM modules](https://v3.nuxtjs.org/guide/going-further/esm#what-are-valid-imports-in-a-nodejs-context).

There are two entries to inspect:
- `.nuxt/dev/index.mjs` (nitro bundle)
- `.nuxt/server/server.mjs` (vite bundle for nuxt app) <-- issue is here

Searching for `import ` and `import()`, there is the problematic import line in vite bundle:

```js
import("file:///home/pooya/tmp/supabase_error/node_modules/@supabase/postgrest-js/dist/module/lib/types.js")
```

The issue is that `@supabase/postgreest-js` has filed using ESM syntax but does not comply with what Node.js expects for ESM modules to use `.mjs` extension or `type: "module"` in its package.json. Now with Nuxt 3, we took some smart ideas to **automatically detect** this situation and inline the dependency using vite or rollup that can handle such mixed syntax. ([unjs/externality](https://github.com/unjs/externality) and [unjs/mlly#isValidNodeImport](https://github.com/unjs/mlly#isvalidnodeimport)). 

This was automatically working until `postgrest-js@0.37.3` because [types.js](https://unpkg.com/browse/@supabase/postgrest-js@0.37.3/dist/module/lib/types.js) had an import statement without `type: module` and `.mjs` ext. But in [`0.37.4`](https://unpkg.com/browse/@supabase/postgrest-js@0.37.4/dist/module/lib/types.js) that import was removed and regex in mlly wasn't enough to cover.

So how is the fix and steps:
- Supabase module should explicitly add all esm-incompatible `@supabase/` packages explicitly to thee `build.transpile` step to avoid such regressions when automated detector doesn't works. This alone also fixes the issue
- Improving mlly syntax detection to detect `export class` and categorize as ESM
- Ask `@supabase` libraries to fix ESM issue. Solution is as easy as adding a package.json to the `dist/module/` with `type: module` or (much better) use `.mjs`/`.cjs` syntax.

**Comment by larbish** [comment] 2022-06-29 09:28
You can now remove the temporary fix, this issue should be fixed on `v0.1.18` thanks to #55 and should also be fixed on other version thanks to [mlly update](https://github.com/unjs/mlly/commit/896c8a7dd087d041ffb29a00065a4f71d62ed249). Thanks @pi0 !

**Comment by michaelpumo** [comment] 2022-06-29 10:12
> You can now remove the temporary fix, this issue should be fixed on `v0.1.18` thanks to #55 and should also be fixed on other version thanks to [mlly update](https://github.com/unjs/mlly/commit/896c8a7dd087d041ffb29a00065a4f71d62ed249). Thanks @pi0 !

Thank you, this resolved the issue for me.

**Comment by pi0** [comment] 2022-06-29 15:44
Thanks for reaching out @soedirgo <3 Would be definitely happy to help improve isomorphic builds. Also indeed it is strange but at same time makes sense to pick ESM syntax over CJS using `module` field when available. If there is an `exports` field, it will be picked...

**Comment by soedirgo** [comment] 2022-06-29 15:48
> If there is an exports field, it will be picked...

Interesting - I'll test it out on the repro link above.

**Comment by pi0** [comment] 2022-06-29 15:52
Also please check out [unjs/unbuild](https://github.com/unjs/unbuild). It is specifically designed for ESM friendly libs.

**Comment by liuzycc** [comment] 2022-08-16 09:43
version: Nuxt 3.0.0-rc.6
The same error as above turned out to be a three-way dependency package problem
solution：
nuxt.config.js: 
  build: { transpile: ["three"] }

**Closed** 2022-08-22 09:29 UTC
Labels: bug
